# Generated by Django 6.0.3 on 2026-03-17 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecursoAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TEL', 'Telefone'), ('SITE', 'Site'), ('RED', 'Rede Social')], max_length=4)),
                ('valor', models.CharField(max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='example.tagproblema')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tags', models.ManyToManyField(to='example.tagproblema')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='problemas',
            field=models.ManyToManyField(blank=True, to='example.tagproblema'),
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
