# Generated by Django 6.0.3 on 2026-06-16 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_comunidade_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='membros_pendentes',
            field=models.ManyToManyField(blank=True, related_name='comunidades_pendentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
