# Generated by Django 6.0.3 on 2026-06-16 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_comunidade_membros_pendentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='membros_silenciados',
            field=models.ManyToManyField(blank=True, related_name='comunidades_silenciadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
